config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show, :edit, :update]

  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
  get 'users/follow_list/:user_id' => 'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'

  resources :products, only: :show do
    resources :reviews, only: [:create]
  end

  post   '/like/:product_id' => 'likes#create',   as: 'like_create'
  delete '/like/:product_id' => 'likes#destroy', as: 'like_destroy'

  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.where('date LIKE(?)', "%#{params[:keyword]}%").order("date DESC").page(params[:page]).per(8)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.includes(:user)
  end
end

app/views/products/_like.html.erb
<div class="like-link" id="like-link-<%= product.id %>">

  <% if current_user && current_user.likes.find_by(product_id: product.id)  %>
    <%= link_to like_destroy_path(product.id), method: :delete, remote: true do %>
      <div class = "iine__button">★<%= product.likes_count %></div>
    <% end %>
  <% else %>
    <%= link_to like_create_path(product.id), method: :post, remote: true do %>
        <div class = "iine__button">☆<%= product.likes_count %></div>
    <% end %>
  <% end %>

</div>

app/views/products/_product.html.erb
<div class = "product">
  <div class = "product__image">
    <a href="/products/<%=product.id%>"><img src=<%= product.image_url %> class="activator" ></a>
  </div>
  <div class = "product__bottom">
    <%= render 'products/like', product: product %>
    <div class = "product__bottom__title">
      <a><%= link_to product.title, product_path(product.id) %></a>
    </div>
    <div class = "product__bottom__date">
      <a><%= product.date%></a>
    </div>
    <div class = "product__bottom__link">
      <%= link_to "オフィシャルページへ", product.link %>
    </div>
  </div>
</div>

app/views/products/_review.html.erb
<div class = "review">
  <% if review.user.image? %>
    <img src = <%= review.user.image %> class = "icon_image">
  <% else %>
    <%= image_tag 'no-image.jpeg' ,class: "icon_image"%>
  <% end %>
  <div class = "review__right">
    <%= link_to review.user.name, "/users/#{review.user.id}"%>
    <p>
      <%= review.text  %>
      <%= link_to "放送日:#{review.product.date}", "/products/#{review.product.id}",class: "review__link" %>
    </p>
  </div>
</div>

app/views/products/index.html.erb
<div class = "serch">
  <%= form_tag(root_path, method: :get) do %>
  <input class="search__input" name="keyword" placeholder="日付で検索" type="text" >
  <input class="action btn pink lighten-3" type = "submit" name ="commit" value="検索">
  <% end %>
</div>

<div class = "products">
  <% @products.each do |product| %>
    <%= render :partial => "product", :locals => { product: product } %>
  <% end %>
</div>

<div class = "paginate">
  <%= paginate @products %>
</div>

app/views/products/show.html.erb
<div class = "products">
  <%= render :partial => "product", :locals => { product: @product } %>
</div>

<div class = "review-zone" >

  <div class = "form">
    <%= form_tag("/products/#{@product.id}/reviews", method: :post, id: "new_review") do %>
      <textarea name="text" placeholder="コメントする"></textarea>
      <input type="submit" value="送信">
    <% end %>
  </div>

  <div class = "reviews">
    <h3>< リトルトゥースの声 ></h3>
      <% @reviews.each do |review| %>
        <%= render :partial => "review", :locals => { review: review }%>
      <% end %>
  </div>

</div>